### ISSUE TITLE
Add suport to Upstart services on Ubuntu 16.04

### ISSUE THREAD

**Issue by igorbrites** [byjg/php-daemonize#1]
After installing a service on Ubuntu 16.04, the command `service my-service status` returns this:

```
● my-service.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

And when I try to start, this:

```
Failed to start my-service.service: Unit my-service.service not found.
```

I have to run `/etc/init.d/my-service start` to run.

**Comment by byjg** [comment]
Hey!

Installing in /etc/init.d on Ubuntu 16.04 requires to you use update-rc.d command. 

But, I created a version where you can install directly to Upstart (defaults to Ubuntu 16.04). 

Follow the steps: 

Install the dev version: 1.3 

```
composer require "byjg/php-daemonize=1.3.*"
```

The new command will be available:

```
daemonize install --template=upstart ........ 
```

Remember to uninstall the previous versions before install the upstart template. 

Please let me know if it works fine. If it is OK I'll merge this branch and generate a new release. 

Thank you.

**Comment by igorbrites** [comment]
Same problem John =(

**Comment by byjg** [comment]
I got it!!

Ubuntu 16.04 does not use Upstart. The service is managed by "SystemD". Because of this is not working. 

Please, get the most recent version of the development branch 1.3 and use the command:

```
composer global require "byjg/php-daemonize=1.3.*" // or compose global update
daemonize install --template=systemd my-service "\My\Process\Daemon::execute" "vendor/autoload.php" "/opt/my-project" "" param=value
```

The templates available are -> initd (or systemv), upstart and systemd

*Important note* --> This version is incompatible with previous versions, so make it sure there is no old services installed.

**Comment by byjg** [comment]
Bump.

May I close this issue?

**Comment by byjg** [comment]
Closed without answer.
